wstta_bt_node:
  ros__parameters:
    use_sim_time: true
    joint_state_topic: "/joint_states"
    # predefined state for the group arm
    arm_predefined_states: ["arm_drop_prod_pose",
                          "before_drop_prod_pose","arm_initial_pose"]
 
    ee_predefined_states: ["close","open","grasp"]
    
    base_long_path_pose: [5.0,7.0,0.0,0.0]
    base_initial_pose: [0.0,0.0,0.0,0.0]
    #define poses where robot can unload when container is full
    unload_poses: [9.0,8.0,0.0,0.0]
    circle_radius: 0.315000
    base_frame: base_footprint
    #tree_xml_file : "$(find-pkg-share mm_behaviors)/xml_tree/mm_behaviors.xml"
