# controller_manager provides the necessary infrastructure to manage multiple controllers efficiently and robustly using ROS 2 Control.
controller_manager:
  ros__parameters:
    update_rate: 100 # update_rate specifies how often (in Hz) the controllers should be updated.
    use_sim_time: true
    # The JointTrajectoryController allows you to send joint trajectory commands to a group 
    # of joints on a robot. These commands specify the desired positions for each joint.     
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    mm_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    # differential drive controller for the wheels
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    sine_controller:
      type: sine_law_controller/SineLawController

    # Responsible for publishing the current state of the robot's joints to the /joint_states 
    # ROS 2 topic
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
   
    
joint_state_broadcaster:
  ros__parameters:
    use_sim_time: true
# Define the parameters for each controller
arm_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - arm_joint1
      - arm_joint2
      - arm_joint3
      - arm_joint4
    # The controller will expect position commands as input for each of these joints.
    command_interfaces:
      - position
    
    
    # Tells the controller that it should expect to receive position data as the state 
    # feedback from the hardware interface,
    state_interfaces:
      - position
      - velocity
    # If true, When set to true, the controller will not use any feedback from the system 
    # (e.g., joint positions, velocities, efforts) to compute the control commands. 
    open_loop_control: false

    # When set to true, it allows the controller to integrate the trajectory goals it receives. 
    # This means that if the goal trajectory only specifies positions, the controller will 
    # numerically integrate the positions to compute the velocities and accelerations required 
    # to follow the trajectory.
    allow_integration_in_goal_trajectories: true
    # Allow non-zero velocity at the end of the trajectory
    allow_nonzero_velocity_at_trajectory_end: true

diff_drive_controller:
  ros__parameters:
    use_sim_time: true
    cmd_vel_timeout: 2.0
    publish_rate: 50.0
    # Wheel Joints (must match URDF exactly)
    left_wheel_names: ["left_front_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint"]

    # Robot Geometry
    wheel_separation: 0.4   # Distance between left and right wheel center [m]
    wheel_radius: 0.0625       # Radius of the wheels [m]

    # Odometry Configuration
    odom_frame_id: odom
    base_frame_id: base_footprint
    open_loop: false        # Use feedback (true) or just commands (false)
    enable_odom_tf: true    # Publish the odom -> base_footprint transform
    
    # Velocity Limits (Optional but recommended)
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.5
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 3.0
  

sine_controller:
  ros__parameters:
    joints:
      -arm_joint1
      -arm_joint2
mm_gripper_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - ee_actuated_tooth_joint
    # The controller will expect position commands as input for each of these joints.
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    open_loop_control: false

    allow_integration_in_goal_trajectories: true
    # Allow non-zero velocity at the end of the trajectory
    allow_nonzero_velocity_at_trajectory_end: true
    