# Use the official ROS Jazzy desktop full base image
# Use the official ROS Jazzy desktop full base image
FROM osrf/ros:jazzy-desktop-full


#Name of docker user as argument 
ARG docker_user_name
# Name of the ros workspace to mount
ARG ros_ws

# The group identifier and User identifier for user creation
ARG GID=1000
ARG UID=1000

# Set up environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV HOME="/home/$docker_user_name"
ENV ROS_DISTRO=jazzy
ENV ROS_WS=${HOME}/$ros_ws


# Delete user if it exists in container (Ubuntu Noble: ubuntu)
RUN if id -u $UID ; then userdel `id -un $UID` ; fi

# Add user and install sudo
RUN groupadd --gid $GID $docker_user_name && useradd --uid $UID --gid $docker_user_name --shell /bin/bash --create-home $docker_user_name \
    && apt-get update && apt-get install -y sudo \
    && echo "$docker_user_name ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# Install necessary dependencies
RUN apt-get update && apt-get -y upgrade && apt-get install -y \
    git \
    python3-pip \
    python3-colcon-common-extensions \
    python3-vcstool \
    && rm -rf /var/lib/apt/lists/*


# Install MoveIt 2, ROS 2 Control, and their dependencies
RUN apt-get update && apt-get install -y \
    ros-${ROS_DISTRO}-urdf-launch \
    ros-${ROS_DISTRO}-urdf-tutorial \
    ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
    ros-${ROS_DISTRO}-joint-state-publisher \
    ros-$ROS_DISTRO-joint-state-publisher-gui \
    ros-${ROS_DISTRO}-rqt-tf-tree \
    ros-${ROS_DISTRO}-rqt-graph \
    ros-${ROS_DISTRO}-ur-description \ 
    ros-${ROS_DISTRO}-turtlebot4-description \ 
    ros-${ROS_DISTRO}-leo-description \
    && rm -rf /var/lib/apt/lists/*

# Copy ros ws entry point
COPY ros_ws_entrypoint.sh /ros_entrypoint.sh
RUN chmod +x /ros_entrypoint.sh
# Set ownership to user
RUN chown -R $docker_user_name:$docker_user_name ${HOME}

RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /etc/bash.bashrc && \
    echo "source $ROS_WS/install/setup.bash" >> /etc/bash.bashrc

# Switch to user
USER $docker_user_name

WORKDIR $ROS_WS

# Entrypoint
ENTRYPOINT ["/ros_entrypoint.sh"]
